services:

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  db:
    container_name: mysql
    image: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=lara-docker
      - MYSQL_ROOT_PASSWORD=password

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - "3307:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=password
    depends_on:
      - db

  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    depends_on:
      - db
